In [1]:
import numpy as np 
import matplotlib.pyplot as plt
import pandas as pd
import sklearn 
import seaborn as sns

In [2]:
data = pd.read_csv('Datasets/usuarios.csv')
data.head()

,duracion,paginas,acciones,valor,clase
0,7.0,2,4,8,2
1,21.0,2,6,6,2
2,57.0,2,4,4,2
3,101.0,3,6,12,2
4,109.0,2,6,12,2


In [3]:
len(np.unique(data['clase']))

3

In [4]:
data.isnull().sum()

duracion    0
paginas     0
acciones    0
valor       0
clase       0
dtype: int64

In [5]:
lista = [x for x in data.columns if x != 'clase']

In [6]:
x = np.array(data[lista])
y = np.array(data['clase'])

In [7]:
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()
x = scaler.fit_transform(x)

In [8]:
from sklearn.model_selection import train_test_split

x_train, x_test, y_train, y_test = train_test_split(x,y, test_size=0.2)

In [9]:
from sklearn.linear_model import LogisticRegression

log = LogisticRegression()
log.fit(x_train, y_train)

LogisticRegression()

In [10]:
y_pred = log.predict(x_test)

In [11]:
y_pred

array([0, 2, 2, 0, 2, 0, 0, 0, 1, 0, 2, 2, 1, 2, 0, 0, 0, 2, 2, 0, 2, 0,
       0, 0, 0, 0, 0, 0, 0, 2, 2, 2, 2, 1])

In [12]:
from sklearn.metrics import confusion_matrix

In [13]:
confusion_matrix(y_test,y_pred)

array([[13,  1,  2],
       [ 4,  2,  1],
       [ 1,  0, 10]])

In [14]:
from sklearn.metrics import classification_report

print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

           0       0.72      0.81      0.76        16
           1       0.67      0.29      0.40         7
           2       0.77      0.91      0.83        11

    accuracy                           0.74        34
   macro avg       0.72      0.67      0.67        34
weighted avg       0.73      0.74      0.71        34



In [15]:
log.intercept_, log.coef_

(array([ 1.0468293 ,  0.21758873, -1.26441803]),
 array([[-0.34330871, -0.39835244,  1.24259214,  0.73459058],
        [ 0.22998304, -0.03692716, -0.97838088,  2.19233972],
        [ 0.11332566,  0.4352796 , -0.26421126, -2.9269303 ]]))

In [16]:
num_datos = len(y)
num_clases = len(np.unique(y))
y_one = np.zeros((num_datos, num_clases))
for i in range(num_datos):
    y_one[i,y[i]] = 1
    
y_one

array([[0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1

In [17]:
from Fisica.regresion_logistica import RegresionLogistica

In [18]:
rl = RegresionLogistica()


In [19]:
rl.fit(x_train,y_train)

In [20]:
rl.intercept, rl.coef

(array([ 1.1147577 ,  0.23098369, -1.34574138]),
 array([[-0.39318939, -0.51648789,  1.70110632,  0.50881613],
        [ 0.24924168, -0.06184158, -1.11690544,  2.41618228],
        [ 0.14394771,  0.57832946, -0.58420088, -2.92499841]]))