## Regresión de Ridgen ##

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [2]:
data = pd.read_csv('Datasets/Customer Churn Model.txt')
data.head(2)

,State,Account Length,Area Code,Phone,Int'l Plan,VMail Plan,VMail Message,Day Mins,Day Calls,Day Charge,...,Eve Calls,Eve Charge,Night Mins,Night Calls,Night Charge,Intl Mins,Intl Calls,Intl Charge,CustServ Calls,Churn?
0,KS,128,415,382-4657,no,yes,25,265.1,110,45.07,...,99,16.78,244.7,91,11.01,10.0,3,2.7,1,False.
1,OH,107,415,371-7191,no,yes,26,161.6,123,27.47,...,103,16.62,254.4,103,11.45,13.7,3,3.7,1,False.


In [3]:
x = ['Night Mins','Night Calls']
x = np.array(data[x])
y = ['Night Charge']
y = np.array(data[y])

In [4]:
#Escalador
from sklearn.preprocessing import StandardScaler

In [5]:
scaler = StandardScaler()

In [6]:
x = scaler.fit_transform(x)
y = scaler.fit_transform(y)

In [7]:
print(x)

[[ 0.86674322 -0.46549436]
 [ 1.05857074  0.14782467]
 [-0.75686906  0.19893459]
 ...
 [-0.1774313  -0.46549436]
 [-1.21962822  1.88556193]
 [ 0.80148231 -1.18103324]]


In [8]:
from sklearn.model_selection import train_test_split

In [9]:
x_train, x_test, y_train, y_test = train_test_split(x,y, test_size = 0.2) 

In [10]:
from sklearn.linear_model import Ridge

In [11]:
ridge = Ridge(alpha = 0.1)

In [12]:
ridge.alpha

0.1

In [13]:
ridge.fit(x_train, y_train)

Ridge(alpha=0.1)

In [14]:
ridge.intercept_, ridge.coef_

(array([9.29699214e-06]), array([ 9.99966098e-01, -3.18768479e-05]))

In [15]:
y_pred = ridge.predict(x_test)

In [16]:
from sklearn.metrics import r2_score

In [17]:
r2_score(y_test,y_pred)

0.9999983704944747

## Regresión de Lasso ##

In [18]:
from sklearn.linear_model import Lasso

In [19]:
lasso = Lasso(alpha = 0.1)

In [20]:
lasso.fit(x_train, y_train)

Lasso(alpha=0.1)

In [21]:
lasso.intercept_, lasso.coef_

(array([-0.0004349]), array([0.90038567, 0.        ]))

In [22]:
y_pred_l = lasso.predict(x_test)

In [23]:
r2_score(y_test,y_pred_l)

0.9900732530817675

In [24]:
from Fisica.modelo_lineal import Ridge
from Fisica.modelo_lineal import Lasso

In [25]:
rid = Ridge()
las = Lasso()

In [26]:
rid.fit(x_train,y_train)
las.fit(x_train,y_train)

In [27]:
rid.intercept, rid.coef

(array([9.2966434e-06]),
 array([[ 9.99966098e-01],
        [-3.18768512e-05]]))

In [28]:
las.intercept, las.coef

(array([-2.37485363]),
 array([[529.60867002],
        [  0.        ]]))

In [33]:
y_pred_r = rid.predict(x_test)
y_pred_l = las.predict(x_test)

In [34]:
r2_score(y_test,y_pred_r)

0.9999983704945071

In [35]:
r2_score(y_pred,y_pred_l)

-279495.40343180025